### ISSUE TITLE
Readme and examples don't reflect repeat() behavior

### ISSUE THREAD

**Issue by nimne** [jrullan/neotimer#4]
Hello,

The default behavior of `repeat()` was changed in the commit on Aug 13, 2017. The readme and examples don't reflect the change,  passing an int to `repeat()` now causes it to repeat that many times, rather than the repeat happening that many milliseconds.

The readme should use `mytimer.repeat()` rather than `mytimer.repeat(2000)`, and this is also true in the repeat.ino example.

-Nick

**Comment by carmolim** [comment]
Yes, I just found this out!

**Comment by jrullan** [comment]
@nimne and @carmolim 

Guys, you are so right!! I'm sorry I didn't notice this on the last update. I have already updated the documentation and the examples to reflect the updated functionality of repeat(). In the README.md there are some examples of how to use the repeat mode and the repeatReset as well.
